name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
      
jobs:

  ci:
    name: Run checks and tests over Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
      strategy:
        matrix:
          otp: ['23.3', '24.3', '25.3']
      steps:
        - uses: actions/checkout@v3
        - uses: erlef/setup-beam@v1
          with:
            otp-version: ${{matrix.otp}}
            rebar3-version: '3.14'
        - run: rebar3 test
